image: node:20

pipelines:
  branches:
    dev:
      - step:
          name: Code Validation (Build & Test)
          caches:
            - node
          script:
            - npm install --legacy-peer-deps
      - step:
          name: Add Known Host
          script:
            - ssh-keyscan www.bytesbrick.com >> ~/.ssh/known_hosts
      - step:
          name: Deploy Code To The Remote Server
          deployment: development
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: 'www-data'
                SERVER: 'www.bytesbrick.com'
                COMMAND: 'cd /var/www/html/beta.technovaticsolutions.com &&  git pull origin dev && rm -rf .next && npm install --legacy-peer-deps && npm run build && pm2 restart beta.technovaticsolutions.com'
                DEBUG: 'true'
